commonLabels:
  region: fraction
resources:
- ../base/longhorn
- ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: basic-auth
  namespace: longhorn-system
  files:
  - secrets/auth
