kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi-targetd-vg-targetd
parameters:
  targetPortal: 172.18.13.124:3260
  iqn: iqn.2020-05.cloud.unstable:targetd
  initiators: iqn.2020-04.cloud.unstable:172.18.13.111,iqn.2020-04.cloud.unstable:172.18.13.112,iqn.2020-04.cloud.unstable:172.18.13.113,iqn.2020-04.cloud.unstable:172.18.13.121,iqn.2020-04.cloud.unstable:172.18.13.122,iqn.2020-04.cloud.unstable:172.18.13.123,iqn.2020-04.cloud.unstable:172.18.13.124
  chapAuthDiscovery: "false"
  chapAuthSession: "false"
