kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi-targetd-vg-targetd
parameters:
  targetPortal: 172.18.13.124:3260
  iqn: iqn.2020-05.cloud.unstable:targetd
  initiators: iqn.2020-04.cloud.unstable:node111,iqn.2020-04.cloud.unstable:node112,iqn.2020-04.cloud.unstable:node113,iqn.2020-04.cloud.unstable:node121,iqn.2020-04.cloud.unstable:node122,iqn.2020-04.cloud.unstable:node123,iqn.2020-04.cloud.unstable:node124
  chapAuthDiscovery: "false"
  chapAuthSession: "false"
