resources:
- ../base/kube-prometheus/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: kp-config
  namespace: monitoring
  behavior: merge
  literals:
  - DOMAIN=unstable.cloud

secretGenerator:
- name: alertmanager-main
  namespace: monitoring
  behavior: merge
  files:
  - secrets/alertmanager.yaml
- name: basic-auth
  namespace: monitoring
  files:
  - secrets/auth
