apiVersion: v1
kind: Service
metadata:
  name: ing-ingress-nginx-controller
  namespace: ingress
spec:
  loadBalancerIP: 2405:6581:8580:301:face:b00c:888:999
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
